# Generated by Django 4.2.7 on 2023-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailRecord',
            fields=[
                ('call_id', models.UUIDField(primary_key=True, serialize=False)),
                ('caller_number', models.CharField(max_length=20)),
                ('callee_number', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('call_type', models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming'), ('missed', 'Missed')], max_length=10)),
                ('call_status', models.CharField(choices=[('successful', 'Successful'), ('unanswered', 'Unanswered'), ('rejected', 'Rejected')], max_length=15)),
            ],
        ),
    ]
